import Seo from '@/components/Seo'
import { CONTACT_EMAIL } from '@/constants/nav'
import { ABN, LEGAL_ENTITY_NAME } from '@/constants/business'

// Per the client (2026-07-13): kept as close to his original terms of service
// (bobisontattoo.com/tos, Enzuzo-generated) as possible — only the business
// name/entity and domain are swapped for the studio. Sections that don't
// technically apply here (mobile app/EULA, online orders/shipping) are kept
// in at his explicit request, matching what was on his original site.
//
// Adapted boilerplate, not legal advice — recommend real legal review before
// launch, same as the privacy policy.
const SECTIONS = [
  {
    heading: '1. Introduction',
    body: `Our aim is to keep this Agreement as readable as possible, but in some cases for legal reasons, some of the language is required "legalese".

This terms of service document was generated by Enzuzo, our data privacy and compliance vendor, using information and details specific to our business.`,
  },
  {
    heading: '2. Your Acceptance of this Agreement',
    body: `These terms of service are entered into by and between You and ${LEGAL_ENTITY_NAME} (ABN ${ABN}), trading as Bobby's Tattoo ("Company," "we," "our," or "us"). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively "Terms of Service"), govern your access to and use of bobbystattoo.com, including any content, functionality, and services offered on or through bobbystattoo.com (the "Website"). We offer the following service that is subject to these Terms of Service: Tattooing (collectively "Services").

Please read the Terms of Service carefully before you start to use the Website.

By using the Website [or by clicking to accept or agree to the Terms of Service when this option is made available to you], you accept and agree to be bound and abide by these Terms of Service and our Privacy Policy, incorporated herein by reference. If you do not want to agree to these Terms of Service, you must not access or use the Website.

You must be at least 13 years old to use this Website. However, children of all ages may use the Website if enabled by a parent or legal guardian. If you are under 18, you represent that you have your parent or guardian's permission to use the Website. Please have them read these Terms of Service with you.

If you are a parent or legal guardian of a user under the age of 18, by allowing your child to use the Website, you are subject to the terms of these Terms of Service and responsible for your child's activity on the Website.

BY ACCESSING AND USING THIS WEBSITE, YOU:

ACCEPT AND AGREE TO BE BOUND AND COMPLY WITH THESE TERMS OF SERVICE;
YOU REPRESENT AND WARRANT THAT YOU ARE THE LEGAL AGE OF MAJORITY UNDER APPLICABLE LAW TO FORM A BINDING CONTRACT WITH US; AND,
YOU AGREE IF YOU ACCESS THE WEBSITE FROM A JURISDICTION WHERE IT IS NOT PERMITTED, YOU DO SO AT YOUR OWN RISK.`,
  },
  {
    heading: '3. Updates to Terms of Service',
    body: `We may revise and update these Terms of Service from time to time in our sole discretion. All changes are effective immediately when we post them and apply to all access to and use of the Website thereafter.

Continuing to use the Website or making subsequent purchases following the posting of revised Terms of Service means that you accept and agree to the changes. You are expected to check this page each time you access this Website so you are aware of any changes, as they are binding on you.`,
  },
  {
    heading: '4. Your Responsibilities',
    body: `You are required to ensure that all persons who access the Website are aware of this Agreement and comply with it. It is a condition of your use of the Website that all the information you provide on the Website is correct, current, and complete.

YOU ARE SOLELY AND ENTIRELY RESPONSIBLE FOR YOUR USE OF THE WEBSITE AND YOUR COMPUTER, INTERNET AND DATA SECURITY.`,
  },
  {
    heading: '5. Prohibited Activities',
    body: `You may use the Website only for lawful purposes and in accordance with these Terms of Service. You agree not to use the Website:

In any way that violates any applicable federal, state, local or international law or regulation (including, without limitation, any laws regarding the exports of data software to and from the U.S. or other countries).
For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information or otherwise.
To send, knowingly receive, upload, download, use, or re-use any material that does not comply with the Submission Standards set out in these Terms of Service.
To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail," "chain letter," "spam," or any other similar solicitation.
To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other persona or entity (including, without limitation, by using email addresses associated with any of the foregoing).
To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the website, or which as determined by us, may harm the Company or users of the website, or expose them to liability.

Additionally, you agree not to:

Use the Website in any manner that could disable, overburden, damage, or impair the site or interfere with any other party's use of the Website, including their ability to engage in real-time activities through the Website.
Use any robot, spider, or other automatic device, process, or means to access the Website for any purpose, including monitoring or copying any of the material on the Website.
Use any manual process to monitor or copy any of the material on the Website, or for any other purpose not expressly authorized in these Terms of Service, without our prior written consent.
Use any device, software, or routine that interferes with the proper working of the Website.
Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.
Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Website, the server on which the Website is stored, or any server, computer, or database connected to the Website.
Attack the Website via a denial-of-service attack or a distributed denial-of-service attack.
Otherwise attempting to interfere with the proper working of the Website.`,
  },
  {
    heading: '6. Intellectual Property Rights',
    body: `The Website and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by the Company, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.

You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website, except as follows:

Your computer may temporarily store copies of such material in RAM incidental to your accessing and viewing those materials.
You may store files that are automatically cached by your Web browser for display enhancement purposes.
You may print or download one copy of a reasonable number of pages of the Website.
If we provide desktop, mobile or other applications for download, you may download a single copy to your computer or mobile device, provided you agree to be bound by our End User License Agreement for such applications.

You must not:

Modify copies of any materials from this site.
Delete or alter any of the copyright, trademark, or other proprietary rights notices from copies of materials from this site.

If you print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Website in breach of the Terms of Service, your right to use the Website will stop immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title, or interest in or to the Website or any content on the Website is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Website not expressly permitted by these Terms of Service is a breach of these Terms of Service and may violate copyright, trademark, and other laws.`,
  },
  {
    heading: '7. Our Rights',
    body: `We have the right, without provision of notice to:

Take appropriate legal action, including, without limitation, referral to or cooperation with law enforcement or regulatory authorities, or notifying the harmed party of any illegal or unauthorized use of the Website; and
Terminate or suspend your access to all or part of the Website for any or no reason, including, without limitation, any violation of these Terms of Service.

YOU WAIVE AND HOLD HARMLESS COMPANY AND ITS PARENT, SUBSIDIARIES, AFFILIATES, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, AND SUCCESSORS FROM ANY AND ALL CLAIMS RESULTING FROM ANY ACTION TAKEN BY THE COMPANY AND ANY OF THE FOREGOING PARTIES RELATING TO ANY, INVESTIGATIONS BY EITHER THE COMPANY OR BY LAW ENFORCEMENT AUTHORITIES.`,
  },
  {
    heading: '8. Third-Party Links and Content',
    body: `For your convenience, this Website may provide links or pointers to third-party sites or third-party content. We make no representations about any other websites or third-party content that may be accessed from this Website. If you choose to access any such sites, you do so at your own risk. We have no control over the third-party content or any such third-party sites and accept no responsibility for such sites or for any loss or damage that may arise from your use of them. You are subject to any terms and conditions of such third-party sites.`,
  },
  {
    heading: '9. Software',
    body: `By downloading our software, you acknowledge and agree to our End User License Agreement ("EULA"). The terms of the EULA will govern your use of the software.`,
  },
  {
    heading: '10. Mobile Application',
    body: `By using our mobile application, you acknowledge and agree to our EULA as well as the following:

1. If the mobile application fails to conform to any applicable warranty, you may notify the applicable application distributor, and the application distributor may refund any applicable purchase price in accordance with its terms and policies, and to the maximum extent permitted by applicable law, the application distributor will have no other warranty obligation with respect to the mobile application;
2. You represent and warrant that (i) you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a "terrorist-supporting" country and (ii) you are not listed on any U.S. government list of prohibited or restricted parties;
3. You must comply with applicable third-party terms of service when using the mobile application; and
4. You acknowledge and agree that the application distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in these Terms of Service, and that each application distributor will have the right to enforce the terms and conditions in this mobile application license contained in these Terms of Use against you as a third-party beneficiary thereof.`,
  },
  {
    heading: '11. Online Orders',
    body: `All orders, purchases or transactions for the sales of goods, digital products, or information made using this Website are subject to the following additional terms and conditions of sale:

You may not order or obtain goods, digital products or information from this Website if you: (i) are prohibited from accessing or using this Website or any of this Website's contents, goods, digital products or information by applicable law or (ii) you are outside the geographic region where the goods, digital products or information are available for purchase;
You agree that your order is an offer to buy, under these Terms of Service, all goods, digital products, or information listed in your order. All orders must be accepted by us or we will not be obligated to sell such goods, digital products or information to you. We may choose not to accept orders at our sole discretion, even after we send you a confirmation email with your order number and details of the items you have ordered; and
All prices, discounts, and promotions posted on this Website are subject to change without notice. The price and currency charged for a goods, digital products or information will be the price and currency advertised on this Website at the time the order is placed, subject to the terms of any promotions or discounts that may be applicable. The price and currency charged will be clearly stated in the shopping cart before you confirm your purchase. Price increases will only apply to orders placed after the time of the increase. Posted prices do not include taxes or charges for shipping and handling. All such taxes and charges will be added to your total pricing and will be itemized in your shopping cart and in your order confirmation email. We strive to display accurate price information; however, we may, on occasion, make inadvertent typographical errors, inaccuracies, or omissions related to pricing and availability. We reserve the right to correct any errors, inaccuracies, or omissions at any time and to cancel any orders arising from such occurrences.

Where an order indicates a license is being purchased:

All uses on this Website of the terms "sell", "sale", "resell", "resale", "purchase", "price", and the like mean the purchase or sale of a license;
You will comply with all terms and conditions of the applicable license Terms of Service for any goods, digital products or information you obtain through this Website, and you will not cause, induce, or permit others' non-compliance with the terms and conditions of any of license Terms of Services for the goods, digital products or information; and
Except for the limited license granted under the relevant license Terms of Service, nothing in these Terms of Service grants any right, title, or interest in or to (including any license under) any intellectual property rights in or relating to, the good, digital product or information, whether expressly, by implication, estoppel, or otherwise. All right, title, and interest in and to the good, digital product or information are and will remain with Company or its licensors, as applicable.

Shipments & Delivery.
Our shipping policy can be found here: .`,
  },
  {
    heading: '12. Disclaimers, Liability and Indemnification',
    body: `YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE WEBSITE, ITS CONTENT, AND ANY GOODS, DIGITAL PRODUCTS, SERVICES, INFORMATION OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT, AND ANY GOODS, SERVICES, DIGITAL PRODUCTS, INFORMATION OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.

YOU ACKNOWLEDGE AND AGREE THAT COMPANY OR ITS RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS MAKE NO WARRANTY, REPRESENTATION, OR ENDORSEMENT WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, SUITABILITY, ACCURACY, CURRENCY, OR AVAILABILITY OF THE WEBSITE OR ITS CONTENTS OR THAT ANY GOODS, SERVICES, DIGITAL PRODUCTS, INFORMATION OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR WEBSITE OR THE SERVER THAT MAKES IT AVAILABLE OR CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR DESTRUCTIVE CODE.

How We Limit Our Liability to You

EXCEPT WHERE SUCH EXCLUSIONS ARE PROHIBITED BY LAW, IN NO EVENT SHALL THE COMPANY NOR ITS RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS BE LIABLE UNDER THESE TERMS OF SERVICE TO YOU OR ANY THIRD-PARTY FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES WHATSOEVER, INCLUDING ANY DAMAGES FOR BUSINESS INTERRUPTION, LOSS OF USE, DATA, REVENUE OR PROFIT, COST OF CAPITAL, LOSS OF BUSINESS OPPORTUNITY, LOSS OF GOODWILL, WHETHER ARISING OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), ANY OTHER THEORY OF LIABILITY, OR OTHERWISE, REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE AND WHETHER OR NOT THE COMPANY WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

Indemnification

To the maximum extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Company, its parent, subsidiaries, affiliates, and their respective directors, officers, employees, agents, service providers, contractors, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your breach of these Terms of Service or your use of the Website including, but not limited to, third-party sites and content, any use of the Website's content and services other than as expressly authorized in these Terms of Service or any use of any goods, digital products and information purchased from this Website.`,
  },
  {
    heading: '13. Privacy Policy',
    body: `Your provision of personal information through the Website is governed by our privacy policy located at bobbystattoo.com/privacy-policy (the "Privacy Policy").`,
  },
  {
    heading: '14. Governing Law',
    body: `The Website and these Terms of Service will be governed by and construed in accordance with the laws of Australia and any applicable federal laws applicable therein, without giving effect to any choice or conflict of law provision, principle, or rule and notwithstanding your domicile, residence, or physical location. Any action or proceeding arising out of or relating to this Website and/or under these Terms of Service will be instituted in the courts of the Country of Australia, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such action or proceeding. You waive any and all objections to the exercise of jurisdiction over you by such courts and to the venue of such courts.

If you are a citizen of any European Union country or Switzerland, Norway or Iceland, the governing law and forum shall be the laws and courts of your usual place of residence.

The parties agree that the United Nations Convention on Contracts for the International Sale of Goods will not govern these Terms of Service or the rights and obligations of the parties under these Terms of Service.`,
  },
  {
    heading: '15. Severability',
    body: `If any provision of these Terms of Service is illegal or unenforceable under applicable law, the remainder of the provision will be amended to achieve as closely as possible the effect of the original term and all other provisions of these Terms of Service will continue in full force and effect.`,
  },
  {
    heading: '16. Entire Terms of Service',
    body: `These Terms of Service constitute the entire and only Terms of Service between the parties in relation to its subject matter and replaces and extinguishes all prior or simultaneous Terms of Services, undertakings, arrangements, understandings or statements of any nature made by the parties or any of them whether oral or written (and, if written, whether or not in draft form) with respect to such subject matter. Each of the parties acknowledges that they are not relying on any statements, warranties or representations given or made by any of them in relation to the subject matter of these Terms of Service, save those expressly set out in these Terms of Service, and that they shall have no rights or remedies with respect to such subject matter otherwise than under these Terms of Service save to the extent that they arise out of the fraud or fraudulent misrepresentation of another party. No variation of these Terms of Service shall be effective unless it is in writing and signed by or on behalf of Company.`,
  },
  {
    heading: '17. Waiver',
    body: `No failure to exercise, and no delay in exercising, on the part of either party, any right or any power hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right or power hereunder preclude further exercise of that or any other right hereunder.`,
  },
  {
    heading: '18. Notice',
    body: `We may provide any notice to you under these Terms of Service by: (i) sending a message to the email address you provide to us and consent to us using; or (ii) by posting to the Website. Notices sent by email will be effective when we send the email and notices we provide by posting will be effective upon posting. It is your responsibility to keep your email address current.

Questions about these Terms can be sent to ${CONTACT_EMAIL}.`,
  },
]

export default function Terms() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-20">
      <Seo title="Terms of Service" noindex />
      <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-3 text-sm text-muted-foreground">Last updated: to be confirmed before launch.</p>

      <div className="mt-12 space-y-8">
        {SECTIONS.map((section) => (
          <div key={section.heading}>
            <h2 className="text-lg font-semibold tracking-tight">{section.heading}</h2>
            <p className="mt-2 whitespace-pre-line text-sm text-muted-foreground">{section.body}</p>
          </div>
        ))}
      </div>
    </article>
  )
}
